apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default "movie-service-service" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride | default "movie-service" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: {{ .Values.fullnameOverride | default "movie-service" }}

