apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: movie-db
spec:
  serviceName: "movie-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: "{{ .Values.movie_db.image.repository }}:{{ .Values.movie_db.image.tag }}"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: movie-db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-db-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: {{ .Values.movie_db.env.POSTGRES_DB }}
      volumeClaimTemplates:
      - metadata:
          name: db-storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: {{ .Values.movie_db.storage.size }}

