apiVersion: v1
kind: Service
metadata:
  name: movie-db-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: movie-db
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: movie-db

