apiVersion: v1
kind: Secret
metadata:
  name: movie-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: movie-db
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.movie_db.env.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.movie_db.env.POSTGRES_PASSWORD | b64enc }}

