apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast-pvc
  labels:
    app.kubernetes.io/name: {{ include "cast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

