apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cast-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "cast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DATABASE_URI: {{ .Values.environments[.Environment].database_uri }}
  CAST_SERVICE_HOST_URL: {{ .Values.environments[.Environment].service_host_url }}

