apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cast-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "cast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.castDb.user }}
  DATABASE_PASSWORD: {{ .Values.castDb.password }}
  DATABASE_URI: {{ .Values.environments[.Environment].database_uri | b64enc }}
  CAST_SERVICE_HOST_URL: {{ .Values.environments[.Environment].service_host_url | b64enc }}

