apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cast-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "cast-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.castDb.user }}
  DATABASE_PASSWORD: {{ .Values.castDb.password }}
  DATABASE_URI: {{ include "cast-service.databaseUri" . }}
  CAST_SERVICE_HOST_URL: {{ include "cast-service.serviceHostUrl" . }}

