# Default values for cast-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: davydatascientest/datascientestapi-cast
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

castDb:
  user: cm9vdA==
  password: ZGF0YXNjaWVudGVzdA==
  name: cast_db_dev

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Environments specific values 
environments:
  dev:
    database_uri: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    service_host_url: http://cast_service_dev:8000/api/v1/casts/
  qa:
    database_uri: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_qa
    service_host_url: http://cast_service_qa:8000/api/v1/casts/
  staging:
    database_uri: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_staging
    service_host_url: http://cast_service_staging:8000/api/v1/casts/
  prod:
    database_uri: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_prod
    service_host_url: http://cast_service_prod:8000/api/v1/casts/

